### PR TITLE
fix webpack error with version beta.23

### PR DESCRIPTION
**Pull request by gabrielbazan7**

### CODE REVIEW

**Comment by bitjson** [comment]
Can we not update to the latest version of Webpack? What's broken in the latest version?

**Comment by gabrielbazan7** [comment]
With 2.3.3 version

windows_10_x64 3

**Comment by bitjson** [comment]
@nacardin is this fixed now? (Can this be closed?)

**Comment by bitjson** [comment]
Closing in favor of https://github.com/bitpay/cordova-plugin-qrscanner/pull/90

**Pull request closed without merging**
