### PR TITLE
Add android platform

### PR DESCRIPTION
**Pull request by willhay**

### CODE REVIEW

**Comment by tobiasviehweger** [comment]
@willhay Very interested in this, just started working on this today. I'm quite new to Cordova plugins, but willing to read up on stuff, in case you need some help :)

**Comment by willhay** [comment]
@tobiasviehweger Great to hear! Just committed the rest of my changes. Most of the methods should now be working besides the scan methods. Currently, QRScanner.java uses the old android.Camera API and it works on old and new devices very well. I think the next step will be to  use the camera2 API for newer devices as well as add the scan methods.

**Comment by tobiasviehweger** [comment]
So I just looked into the best way to read QR codes, and it seems the xzing lib is the way to go. The official phonegap-barcode-scanner is just a wrapper around it as well.

The question is though, if it might make sense to just use https://github.com/journeyapps/zxing-android-embedded this one, also for the CameraPreview. By default they support SurfaceView and TextureView, according to [this page](https://github.com/journeyapps/zxing-android-embedded/blob/master/EMBEDDING.md) might be a better option on newer versions.

I'll play around with this a little...

**Comment by tobiasviehweger** [comment]
This is how I'd imagine it: https://github.com/tobiasviehweger/cordova-plugin-qrscanner/commit/afb730a7dd4271b2caa2bfe0bafa05455eb64bd1

I'm just setting up some test project now to see if everything works..

**Comment by willhay** [comment]
Looks great, testing it out now as well.

**Comment by tobiasviehweger** [comment]
So there was something small missing (starting the actual preview), I've just added that.
Nevertheless, it seems that the opacity of the web view is not correct somewhat, as it still overlays everything.. I'm done for today, maybe you have more success :)

**Comment by willhay** [comment]
image1
@tobiasviehweger

**Comment by tobiasviehweger** [comment]
Ah thanks. So the image preview is already working for me. I'll check on a real device tomorrow if the QR code is also recognized.
clipboard01

**Comment by willhay** [comment]
@tobiasviehweger Just fixed a few things. Trying to get the scan function working now. I'm getting a "java.lang.IllegalStateException: Must be called from the main thread." error on mBarcodeView.decodeSingle(this) (line 448). Same error I was getting for pause/resumePreview. Looking into it now.

**Comment by willhay** [comment]
Everything seems to be working except the scan() (pause, vibrate). It will pause but there is no vibration. This might be a problem with cordova-plugin-vibration, not sure yet. (Line 169 on tests.js has the vibrate function). Testing on a nexus 6P right now and everything looks good besides that. About to test on samsung S3 and S4.

**Comment by bitjson** [comment]
Hey @tobiasviehweger – thanks for your help! This is looking great.

>@bitjson Btw. I have nothing to test the iOS version on, but how exactly is the behavior there? Is the camera shown full screen, with a semitransparent webview?

Yep – the iOS platform renders the camera preview behind the webview, and then makes the webview's background transparent. So it's possible to see the whole camera view by making the webview contents transparent, or to obscure parts and add controls/buttons over the view with HTML/CSS. You can try the browser platform for a good idea of the iOS implementation.

>  Would it be an option to specify a rect in the future, so that you could render it non-fullscreen?

A configurable rect is certainly something we could reconsider. I'd looked at doing that before, but I concluded that it would complicate the API and implementation significantly, without providing much additional functionality.

Particularly for mobile devices, attached cameras are well designed (and optimized) to take and display video on the device's entire screen.

Other rect sizes/ratios would require clipping or distorting the video in order to display the whole image. I don't think we ever want to distort video, and in cases where we want to clip/mask parts of it, we still want to be searching for QR codes across the entire video input. So it makes sense to "crop" the video at the webview layer (by covering it with HTML/CSS interface elements) rather than via an additional native interface.

Does that make sense? Is there another use case you'd like to accommodate with it?

**Comment by tobiasviehweger** [comment]
@willhay Thanks for testing and fixing so thoroughly! The only device available to me currently is the Huawei P8 Lite (running 5.0.1). The current version really worked great on that device! The QR code was almost recognized instantly and the preview image was smooth :) I'll see if I can organize some more phones to test on, that might take a while though.

@bitjson Makes sense. I understood now how everything worked and it's a good option for me - I had feared that the content of the web view might be somewhat transparent as well, but as they aren't, this solution is working quite nicely - the less code used, the less can go wrong ;)

**Comment by tobiasviehweger** [comment]
@willhay Just found this issue, maybe it's just the permission missing?

**Comment by tobiasviehweger** [comment]
https://github.com/journeyapps/zxing-android-embedded/issues/182

**Comment by willhay** [comment]
@tobiasviehweger Looks like the plugin (cordova plugin vibration) is automatically adding the permission to AndroidManifest.xml so I don't think permissions is the problem. I tried making my own vibrate function which worked fine, not sure what's up. I checked out the readme for the cordova plugin vibration and couldn't find anything either. I'll keep looking. Also, when scanning, it looks like the scanning area of zxing is fairly small and you have to put the qrcode at least a foot away from the phone in order for it to work. If I put the qrcode close enough that it takes up most of the camera preview, it doesn't scan at all.

**Comment by tobiasviehweger** [comment]
Hm interesting. When I tested it on the Huawei I didn't experience that. I guess the QR filled at least 2/3 of the screen and worked quite well. Maybe it's really a scaling thing. Does this happen on all your devices?

**Comment by willhay** [comment]
Strange. 
At this distance it works great:
screenshot_20160729-135152

But when you get as close as this it doesn't ever work:
screenshot_20160729-135353

Happens on both the Nexus 6P and Galaxy S4.

**Comment by tobiasviehweger** [comment]
@willhay Thanks for the continued dev. I tested on a Samsung Galaxy A3 today, also worked quite well, though I noticed as well that it does not work if the QR code fills the whole screen. I don't think that's an issue, because having a rect like [this](http://a3.mzstatic.com/eu/r30/Purple2/v4/77/e6/3c/77e63c5b-53fa-df78-9208-1c690bdc7d2f/screen322x572.jpeg) in the app is quite common, and it worked even larger than that for me.

**Comment by willhay** [comment]
@tobiasviehweger No problem, thanks for testing on more devices. I also don't think its a big issue but I'm still looking into whether or not I can/should change the size of the scanning area.

**Comment by willhay** [comment]
The prepare function isn't working on a Galaxy S3 (Android 4.1.2). Looking into it now

**Comment by willhay** [comment]
@tobiasviehweger If you open the test app and click scan() before calling prepare or anything else, it will return- QRScanner.scan() callback returned. {scanning: "1", currentCamera: "0", denied: "0", showing: "0", restricted: "0"…}
Any idea what is causing this?

**Comment by willhay** [comment]
@tobiasviehweger If you restart the test app and click the scan() button in Manual Tests, it won't detect the qrcode or return the data. Click scan() again and it scans and returns fine. If you click prepare() first, then scan(), it detects the qr-code as well. So if you call scan() as your first method call it will not scan.

**Comment by tobiasviehweger** [comment]
@willhay Awesome! Could you remove this line, I think it got committed by accident:
`import com.google.android.gms.games.quest.QuestRef;`

Thanks =)

**Comment by willhay** [comment]
Fixed a lot of stuff. Only issue I can see right now is the scan with pause and vibrate won't vibrate. Trying to fix it now, any ideas whats up? @tobiasviehweger

**Comment by tobiasviehweger** [comment]
@willhay Great to hear that, sorry for coming back late. Unfortunately I'll be on vacation the next two weeks, so not testing from my side. But my latest tests still look very promising..

@bitjson What would be the next steps for getting this one merged?

**Comment by bitjson** [comment]
This is looking great, awesome work guys. @willhay and I just went through some of the final work that needs to be done before this is ready for release. We just need to solve a few more bugs, then a little housekeeping before it's merged. We'll squash out commits labeled `fix` which are not bug fixes for problems with released code, and add breaking change information to the commits that cause the breaks.

Since this has breaking API changes, it will be released as `v3.0.0`, hopefully tomorrow morning.

**Comment by willhay** [comment]
@tobiasviehweger The scanner only detects the QR Code if it's in the middle of the screen. For example, if you position the camera so that the QRCode is in the upper right corner of the BarcodeView preview, the QR Code will not be detected. Once you move the camera so the QR Code is in the middle, it detects it instantly. BarcodeView [details](https://github.com/journeyapps/zxing-android-embedded/blob/master/EMBEDDING.md#notes-on-scaling) how to change the scanning area through a xml file, but since we are adding mBarcodeView in QRScanner.java and not in a layout.xml file, do you have any idea how we can change the scanning area?

**Comment by willhay** [comment]
Closing in favor of https://github.com/bitpay/cordova-plugin-qrscanner/pull/16

**Pull request closed without merging**
