### PR TITLE
UIKit.UIApplication:64:22: note: 'openSettingsURLString' was introduc…

### PR DESCRIPTION
**Pull request by cj4luv**
…ed in Swift 4.2

change  openSettingsURLString:

### CODE REVIEW

**Review by cuni0716 — APPROVED** [review]

**Comment by Towerism** [comment]
This and #271 have been sitting open for a month. Please merge.

**Comment by alexfoo** [comment]
Bumping this too. Please merge.

**Comment by tomaspotok** [comment]
This is a very trivial one. Please merge, breaks our building process.

**Comment by michaelSchrempp** [comment]
would be nice if someone can merge it....

**Comment by zabojad** [comment]
Same here, just had this compile error. Please merge.

**Comment by madsthom** [comment]
Please merge this soon.

**Comment by pedroadame** [comment]
2021 and still not merged...

**Comment by mdledoux** [comment]
@pedroadame - sorry to find your frustration with this so late in the game.  Of all the people in this thread, you might still have this problem.

# Merging the PR is NOT the solution
## The diagnosis of the problem is wrong

However I have come to realize that ***this is not a bug, and that the code does not need to be merged*** - more accurately, it *SHOULD NOT* be merged.  Everyone refers to this as a "bug" and "known issue", but it is not - you simply need a new setting applied.  (admittedly, this is not documented at all)

While it might seem like the maintainers are slacking by NOT merging the PR, what happened is that the module was re-written for Swift 5, and the Pull Request basically asks the maintainers to put old Swift 3 syntax back into place.  The correct thing to do (which works immediately) is to set your Cordova project to use Swift 5, rather than than trying to downgrade Swift 5 code syntax to work with Swift 3.  This is a setting in the iOS section of **config.xml**.
```xml
        <platform name="ios">
            <preference name="UseSwiftLanguageVersion" value="5" />
```

See @daneilzen's comment on March 28, 2020:
https://github.com/bitpay/cordova-plugin-qrscanner/issues/301#issuecomment-629986900 (see the first npmjs URL).  This is THE solution.

It is unfortunate that this has not been made clearer.  I am not sure why this isn't better documented, or why the installer doesn't handle this setting - but the applying of this setting could be more of an Ionic or Cordova issue, and not in the hands of the `cordova-plugin-qrscanner` plugin maintainers.

# Helpful tip
You might need to erase your node_modules and plugins folders before you attempt to rebuild.
I generally do this after making a major change:
```bash
rm -rf node_modules plugins # platforms
npm install
ionic cordova build ios
```
(I forget if it was necessary to erase platforms also...you can try without that first, if you want). \
You should be all set at this point.

# An alternative
If you do have problems, and want to keep your settings at Swift 3 (and want to use a version that works with Swift 3), you can try using this fork of the the March 29, 2019 3.01 edition (still the latest version) - this fork applies the patch:  https://github.com/bitpay/cordova-plugin-qrscanner/pull/271#issuecomment-605522889
```bash
npm uninstall cordova-plugin-qrscanner
npm install git+https://git@github.com/danielzen/cordova-plugin-qrscanner -D
```
Again, this is only if you need to remain at Swift 3 - I do not consider it to be a bug-fix, since technically there is no bug.  The fork keeps the plugin working with Swift 3, **while the official plugin works with Swift 5**.

**Comment by dusty1997** [comment]
> @pedroadame - sorry to find your frustration with this so late in the game. Of all the people in this thread, you might still have this problem.
> 
> However I have come to realize that _**this is not a bug, and that the code does not need to be merged**_ - more accurately, it _SHOULD NOT_ be merged. Everyone refers to this as a "bug" and "known issue", but it is not - you simply need a setting applied.
> 
> While it might seem like the maintainers are slacking by NOT merging the PR, what happened is that the module was re-written for Swift 5, and the Pull Request basically asks the maintainers to put old Swift 3 syntax back into place. The correct thing to do (which works immediately) is to set your project to use Swift 5, rather than than trying to downgrade Swift 5 code syntax to work with Swift 3. This is a setting in the iOS section of **config.xml**.
> 
> ```
>         <platform name="ios">
>             <preference name="UseSwiftLanguageVersion" value="5" />
> ```
> 
> See @daneilzen's comment on March 28, 2020: [#301 (comment)](https://github.com/bitpay/cordova-plugin-qrscanner/issues/301#issuecomment-629986900) (see the first npmjs URL). This is THE solution.
> 
> It is unfortunate that this has not been made clearer. I am not sure why this isn't better documented, or why the installer doesn't handle this setting - but the applying of this setting could be more of an Ionic or Cordova issue, and not in the hands of the qrplugin maintainers.
> 
> # Helpful tip
> You might need to erase your node_modules and plugins folders before you attempt to rebuild. I generally do this after making a major change:
> 
> ```shell
> rm -rf node_modules plugins # platforms
> npm install
> ionic cordova build ios
> ```
> 
> (I forget if it was necessary to erase platforms also...you can try without that first, if you want). You should be all set at this point.
> 
> # An alternative
> If you do have problems, and want to keep your settings at Swift 3 (and want to use a version that works with Swift 3), you can try using this fork of the the March 29, 2019 3.01 edition (still the latest version) - this fork applies the patch: [#271 (comment)](https://github.com/bitpay/cordova-plugin-qrscanner/pull/271#issuecomment-605522889)
> 
> ```shell
> npm uninstall cordova-plugin-qrscanner
> npm install git+https://git@github.com/danielzen/cordova-plugin-qrscanner -D
> ```

Most important comment on github

**Comment by cj4luv** [comment]
the PR closed~!!

**Pull request closed without merging**
